### ISSUE TITLE
expose RTCEncoded(Audio|Video)Frame on workers?

### ISSUE THREAD

**Issue by fippo** [w3c/webrtc-insertable-streams#25]
from @foolip [here](https://github.com/webrtc/samples/pull/1305#issuecomment-630024043):
> https://github.com/alvestrand/webrtc-media-streams/blob/master/explainer.md#api is missing the 
> require Exposed extended attribute, and I can't tell from the rest of the IDL what's intended here. 
> @alvestrand should these interfaces be exposed to workers?

not going to help with my polyfill plans but since they're used in workers they should be exposed there as well.

**Comment by fippo** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2211344 - CL is here if we want to do this. I have questions about writing existence tests but its a straightforward change :-)

**Comment by alvestrand** [comment]
I think this should be done. Fired off the try queue on the Chromium change; that's the fast way to figure out if the syntax checkers like it (and what else needs updating).

**Comment by fippo** [comment]
looking at https://cs.chromium.org/chromium/src/third_party/blink/web_tests/resources/global-interface-listing.js the number of interfaces exposed to the worker seems to be limited to basic types so not sure this is right.

**Comment by alvestrand** [comment]
So the upshot seems to be that Exposed= on interfaces has the meaning described in https://heycam.github.io/webidl/#es-interfaces - that [global object]'s [Typename] attribute is a reference to the interface object of the interface; in practice: its constructor is available through the global object named.

Since workers aren't supposed to be allowed to create either frames or metadata in regular operation, I think we don't need to expose them on workers. In fact, since windows aren't supposed to create them either, do we need to add [Exposed] at all? @foolip probably has an opinion on this.

**Comment by fippo** [comment]
We don't create RTCRtpSenders in JS and still they're exposed so we're a bit inconsistent :-)
:+1: to not exposing them anywhere.

**Comment by domenic** [comment]
If the object is accessible in a given environment (e.g. in windows or workers), then it needs to be [Exposed] there.
